### ISSUE TITLE
Find All Elements does not work

### ISSUE THREAD

**Issue by sebastianciupinski** [GDATASoftwareAG/robotframework-flaui#215]
```
BB
    Launch Application    path=calc.exe
    Sleep     10s
    Find All Elements     //Button
```

result:
```
COMException:  (0x80040201): An event was unable to invoke any of the subscribers (Exception from HRESULT: 0x80040201)
   at Interop.UIAutomationClient.IUIAutomationTreeWalker.GetFirstChildElement(IUIAutomationElement element)
   at FlaUI.UIA3.UIA3TreeWalker.GetFirstChild(AutomationElement element)
   at FlaUI.Core.AutomationElementXPathNavigator.MoveToFirstChild()
   at MS.Internal.Xml.XPath.XPathDescendantIterator.MoveNext()
   at MS.Internal.Xml.XPath.DescendantQuery.Advance()
   at MS.Internal.Xml.XPath.XPathSelectionIterator.MoveNext()
   at FlaUI.Core.AutomationElements.AutomationElement.FindAllByXPath(String xPath)
```

Windows 10 machine

**Comment by noubar** [comment]
@sebastianciupinski 

What you are trying to do is to find all the buttons available in your windows no matter where they are.
In this case it will take long long time for at least 20-30 seconds if you have really no apps other than calc.

According to the error you have provided there is either an app in your windows open which does not support Automation or you have the the same app open twice, as the flaui crawled over it, you got the exception. Which is normal!

I suggest you to make sure there is only one calc app open and to use this code instead

 BB
    Launch Application    path=calc.exe
    Sleep     10s
    Find All Elements     /Window[@Name='Calculator']//Button

**Comment by Nepitwin** [comment]
This is not a bug to search for a button element from root path by UIA2 or UIA3
