### ISSUE TITLE
RFHUB documentation api calls error by documentation update

### ISSUE THREAD

**Issue by Nepitwin** [GDATASoftwareAG/robotframework-flaui#3]
*Steps to reproduce*: 
 * Start rfhub2 server
 * Git clone FlaUiLibrary
 * Go to FlaUILibrary folder
 * Execute rfhub2-cli --mode=update src/FlaUILibrary/keywords/

*Expected result*: 

Keyword documentation for FlaUILibrary should be visualized by rfhub2.

![image](https://user-images.githubusercontent.com/12249055/88543879-e2bc3880-d018-11ea-8bfa-a21be9d4b2f7.png)

*Actual result*:
 * Exception is called by api call

```
root@ID-CH-0581:~/robot-flauilib# rfhub2-cli --mode=update src/FlaUILibrary/keywords/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/robot/utils/importer.py", line 153, in _import
    return __import__(name, fromlist=fromlist)
  File "/root/robot-flauilib/src/FlaUILibrary/keywords/__init__.py", line 1, in <module>
    from .application import ApplicationKeywords
  File "/root/robot-flauilib/src/FlaUILibrary/keywords/application.py", line 1, in <module>
    from FlaUILibrary.core.robotlibcore import keyword
  File "/usr/local/lib/python3.6/dist-packages/FlaUILibrary/__init__.py", line 1, in <module>
    from FlaUILibrary import version, clr
  File "/usr/local/lib/python3.6/dist-packages/FlaUILibrary/clr.py", line 2, in <module>
    import clr
  File "/root/robot-flauilib/src/FlaUILibrary/clr.py", line 8, in <module>
    clr.AddReference(FLAUI_CORE_DLL_PATH)
AttributeError: module 'clr' has no attribute 'AddReference'During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/robot/utils/importer.py", line 68, in import_class_or_module
    imported, source = self._import_class_or_module(name)
  File "/usr/local/lib/python3.6/dist-packages/robot/utils/importer.py", line 79, in _import_class_or_module
    return importer.import_(name)
  File "/usr/local/lib/python3.6/dist-packages/robot/utils/importer.py", line 195, in import_
    module = self._import_by_path(path)
  File "/usr/local/lib/python3.6/dist-packages/robot/utils/importer.py", line 244, in _import_by_path
    return self._import(module_name)
  File "/usr/local/lib/python3.6/dist-packages/robot/utils/importer.py", line 167, in _import
    raise DataError(*get_error_details())
robot.errors.DataError: AttributeError: module 'clr' has no attribute 'AddReference'During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "/usr/local/bin/rfhub2-cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rfhub2/cli/cli.py", line 62, in main
    loaded_collections, loaded_keywords = rfhub_importer.import_libraries()
  File "/usr/local/lib/python3.6/dist-packages/rfhub2/cli/rfhub_importer.py", line 72, in import_libraries
    libraries_paths = self.get_libraries_paths()
  File "/usr/local/lib/python3.6/dist-packages/rfhub2/cli/rfhub_importer.py", line 95, in get_libraries_paths
    libraries_paths.update(self._traverse_paths(Path(path)))
  File "/usr/local/lib/python3.6/dist-packages/rfhub2/cli/rfhub_importer.py", line 107, in _traverse_paths
    if self._is_library_with_init(path):
  File "/usr/local/lib/python3.6/dist-packages/rfhub2/cli/rfhub_importer.py", line 265, in _is_library_with_init
    LibraryDocumentation(str(path)).keywords
  File "/usr/local/lib/python3.6/dist-packages/robot/libdocpkg/__init__.py", line 35, in LibraryDocumentation
    libdoc = builder.build(library_or_resource)
  File "/usr/local/lib/python3.6/dist-packages/robot/libdocpkg/robotbuilder.py", line 32, in build
    lib = TestLibrary(name, args)
  File "/usr/local/lib/python3.6/dist-packages/robot/running/testlibraries.py", line 50, in TestLibrary
    return_source=True)
  File "/usr/local/lib/python3.6/dist-packages/robot/utils/importer.py", line 72, in import_class_or_module
    self._raise_import_failed(name, err)
  File "/usr/local/lib/python3.6/dist-packages/robot/utils/importer.py", line 109, in _raise_import_failed
    raise DataError('\n'.join(msg))
robot.errors.DataError: Importing test library '/root/robot-flauilib/src/FlaUILibrary/keywords' failed: AttributeError: module 'clr' has no attribute 'AddReference'
Traceback (most recent call last):
  File "/root/robot-flauilib/src/FlaUILibrary/keywords/__init__.py", line 1, in <module>
    from .application import ApplicationKeywords
  File "/root/robot-flauilib/src/FlaUILibrary/keywords/application.py", line 1, in <module>
    from FlaUILibrary.core.robotlibcore import keyword
  File "/usr/local/lib/python3.6/dist-packages/FlaUILibrary/__init__.py", line 1, in <module>
    from FlaUILibrary import version, clr
  File "/usr/local/lib/python3.6/dist-packages/FlaUILibrary/clr.py", line 2, in <module>
    import clr
  File "/root/robot-flauilib/src/FlaUILibrary/clr.py", line 8, in <module>
    clr.AddReference(FLAUI_CORE_DLL_PATH)
PYTHONPATH:
  /usr/local/bin
  /usr/lib/python36.zip
  /usr/lib/python3.6
  /usr/lib/python3.6/lib-dynload
  /usr/local/lib/python3.6/dist-packages
  /usr/lib/python3/dist-packages
```

**Comment by Nepitwin** [comment]
Commit https://github.com/GDATASoftwareAG/robotframework-flaui/commit/899aec995a41e663655e5243aa67b9e1e6f7f73f fix this issue. Now we produce a xml files which can be used by rfhub2 directly for all platforms to visualize keyword documentation for rfhub2.

Readme and xml files were updated.
