### ISSUE TITLE
Robotframework could not be installed by Python 3.8.5

### ISSUE THREAD

**Issue by Nepitwin** [GDATASoftwareAG/robotframework-flaui#4]
Hello, 
I would have been interested to try out your rf-library for flaui as White as been deprecated. However, I cannot do so because there is no way to install it.
At least I have not found a way to install it successfully. If I pip install, I end up with a long list of error messages:

```
C:\Users\tuosil\Desktop\kurssikansio\RF_Extended>pip install -U robotframework-flaui
Collecting robotframework-flaui
  Using cached robotframework_flaui-1.3.2-py3-none-any.whl (236 kB)
Collecting pythonnet==2.4.0
  Using cached pythonnet-2.4.0.tar.gz (1.8 MB)
Requirement already satisfied, skipping upgrade: wheel==0.34.2 in c:\python38\lib\site-packages (from robotframework-flaui) (0.34.2)
Requirement already satisfied, skipping upgrade: twine==3.1.1 in c:\python38\lib\site-packages (from robotframework-flaui) (3.1.1)
Requirement already satisfied, skipping upgrade: robotframework-stringformat==0.1.8 in c:\python38\lib\site-packages (from robotframework-flaui) (0.1.8)
Requirement already satisfied, skipping upgrade: robotframework<=3.1.2,>=3.0.4 in c:\python38\lib\site-packages (from robotframework-flaui) (3.1.2)
Requirement already satisfied, skipping upgrade: pdfkit==0.6.1 in c:\python38\lib\site-packages (from robotframework-flaui) (0.6.1)
Requirement already satisfied, skipping upgrade: readme-renderer>=21.0 in c:\python38\lib\site-packages (from twine==3.1.1->robotframework-flaui) (26.0)
Requirement already satisfied, skipping upgrade: requests>=2.20 in c:\python38\lib\site-packages (from twine==3.1.1->robotframework-flaui) (2.24.0)
Requirement already satisfied, skipping upgrade: setuptools>=0.7.0 in c:\python38\lib\site-packages (from twine==3.1.1->robotframework-flaui) (49.6.0)
Requirement already satisfied, skipping upgrade: keyring>=15.1 in c:\python38\lib\site-packages (from twine==3.1.1->robotframework-flaui) (21.3.0)
Requirement already satisfied, skipping upgrade: requests-toolbelt!=0.9.0,>=0.8.0 in c:\python38\lib\site-packages (from twine==3.1.1->robotframework-flaui) (0.9.1)
Requirement already satisfied, skipping upgrade: pkginfo>=1.4.2 in c:\python38\lib\site-packages (from twine==3.1.1->robotframework-flaui) (1.5.0.1)
Requirement already satisfied, skipping upgrade: tqdm>=4.14 in c:\python38\lib\site-packages (from twine==3.1.1->robotframework-flaui) (4.46.0)
Requirement already satisfied, skipping upgrade: docutils>=0.13.1 in c:\python38\lib\site-packages (from readme-renderer>=21.0->twine==3.1.1->robotframework-flaui) (0.16)
Requirement already satisfied, skipping upgrade: Pygments>=2.5.1 in c:\python38\lib\site-packages (from readme-renderer>=21.0->twine==3.1.1->robotframework-flaui) (2.6.1)
Requirement already satisfied, skipping upgrade: bleach>=2.1.0 in c:\python38\lib\site-packages (from readme-renderer>=21.0->twine==3.1.1->robotframework-flaui) (3.1.5)
Requirement already satisfied, skipping upgrade: six in c:\python38\lib\site-packages (from readme-renderer>=21.0->twine==3.1.1->robotframework-flaui) (1.15.0)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\python38\lib\site-packages (from requests>=2.20->twine==3.1.1->robotframework-flaui) (2020.4.5.1)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in c:\python38\lib\site-packages (from requests>=2.20->twine==3.1.1->robotframework-flaui) (2.9)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python38\lib\site-packages (from requests>=2.20->twine==3.1.1->robotframework-flaui) (1.25.9)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in c:\python38\lib\site-packages (from requests>=2.20->twine==3.1.1->robotframework-flaui) (3.0.4)
Requirement already satisfied, skipping upgrade: pywin32-ctypes!=0.1.0,!=0.1.1; sys_platform == "win32" in c:\python38\lib\site-packages (from keyring>=15.1->twine==3.1.1->robotframework-flaui) (0.2.0)
Requirement already satisfied, skipping upgrade: packaging in c:\python38\lib\site-packages (from bleach>=2.1.0->readme-renderer>=21.0->twine==3.1.1->robotframework-flaui) (20.4)
Requirement already satisfied, skipping upgrade: webencodings in c:\python38\lib\site-packages (from bleach>=2.1.0->readme-renderer>=21.0->twine==3.1.1->robotframework-flaui) (0.5.1)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in c:\python38\lib\site-packages (from packaging->bleach>=2.1.0->readme-renderer>=21.0->twine==3.1.1->robotframework-flaui) (2.4.7)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tuosil\\AppData\\Local\\Temp\\pip-install-nsuuprxs\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\tuosil\\AppData\\Local\\Temp\\pip-install-nsuuprxs\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\tuosil\AppData\Local\Temp\pip-wheel-zlu0kwm8'
       cwd: C:\Users\tuosil\AppData\Local\Temp\pip-install-nsuuprxs\pythonnet\
  Complete output (84 lines):
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 5.6.0.
  Update successful.
  MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin\amd64'.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package NUnit.3.7.1.
  Restoring NuGet package NUnit.ConsoleRunner.3.7.0.
  Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\tuosil\AppData\Local\Temp\pip-install-nsuuprxs\pythonnet\packages'
  Adding package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\Users\tuosil\AppData\Local\Temp\pip-install-nsuuprxs\pythonnet\packages'
  Adding package 'NUnit.3.7.1' to folder 'C:\Users\tuosil\AppData\Local\Temp\pip-install-nsuuprxs\pythonnet\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\tuosil\AppData\Local\Temp\pip-install-nsuuprxs\pythonnet\packages'
  Added package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\Users\tuosil\AppData\Local\Temp\pip-install-nsuuprxs\pythonnet\packages'
  Added package 'NUnit.3.7.1' to folder 'C:\Users\tuosil\AppData\Local\Temp\pip-install-nsuuprxs\pythonnet\packages'

  NuGet Config files used:
      C:\Users\tuosil\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      C:\Users\tuosil\.nuget\packages\
      https://api.nuget.org/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

  Installed:
      3 package(s) to packages.config projects
  Traceback (most recent call last):
    File "tools\geninterop\geninterop.py", line 293, in <module>
      sys.exit(main())
    File "tools\geninterop\geninterop.py", line 273, in main
      python_h = preprocess_python_headers()
    File "tools\geninterop\geninterop.py", line 193, in preprocess_python_headers
      for line in _check_output(cmd).splitlines():
    File "tools\geninterop\geninterop.py", line 41, in _check_output
      output = subprocess.check_output(*args, **kwargs)
    File "c:\python38\lib\subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "c:\python38\lib\subprocess.py", line 489, in run
      with Popen(*popenargs, **kwargs) as process:
    File "c:\python38\lib\subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "c:\python38\lib\subprocess.py", line 1307, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\tuosil\AppData\Local\Temp\pip-install-nsuuprxs\pythonnet\setup.py", line 623, in <module>
      setup(
    File "c:\python38\lib\site-packages\setuptools\__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "c:\python38\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\python38\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\tuosil\AppData\Local\Temp\pip-install-nsuuprxs\pythonnet\setup.py", line 610, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "c:\python38\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "c:\python38\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\python38\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\python38\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\python38\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "c:\python38\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "c:\python38\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\tuosil\AppData\Local\Temp\pip-install-nsuuprxs\pythonnet\setup.py", line 298, in build_extension
      subprocess.check_call([sys.executable, geninterop, interop_file])
    File "c:\python38\lib\subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['c:\\python38\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop38.cs']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
DEPRECATION: Could not build wheels for pythonnet which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: pythonnet, robotframework-flaui
  Attempting uninstall: pythonnet
    Found existing installation: pythonnet 2.5.1
    Uninstalling pythonnet-2.5.1:
      Successfully uninstalled pythonnet-2.5.1
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tuosil\\AppData\\Local\\Temp\\pip-install-nsuuprxs\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\tuosil\\AppData\\Local\\Temp\\pip-install-nsuuprxs\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tuosil\AppData\Local\Temp\pip-record-666z57_3\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\pythonnet'
         cwd: C:\Users\tuosil\AppData\Local\Temp\pip-install-nsuuprxs\pythonnet\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
  Rolling back uninstall of pythonnet
  Moving to c:\python38\lib\site-packages\clr.pyd
   from C:\Users\tuosil\AppData\Local\Temp\pip-uninstall-3feume6u\clr.pyd
  Moving to c:\python38\lib\site-packages\python.runtime.dll
   from C:\Users\tuosil\AppData\Local\Temp\pip-uninstall-3feume6u\python.runtime.dll
  Moving to c:\python38\lib\site-packages\pythonnet-2.5.1.dist-info\
   from C:\Python38\Lib\site-packages\~ythonnet-2.5.1.dist-info
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tuosil\\AppData\\Local\\Temp\\pip-install-nsuuprxs\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\tuosil\\AppData\\Local\\Temp\\pip-install-nsuuprxs\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tuosil\AppData\Local\Temp\pip-record-666z57_3\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\pythonnet' Check the logs for full command output.
```

**Comment by Nepitwin** [comment]
Commit https://github.com/GDATASoftwareAG/robotframework-flaui/commit/0020021162b51752cfb6cb81d4c3b4622914567f
will fix it for Python 3.8.X support.
