### ISSUE TITLE
Python 3.10.x compatibility

### ISSUE THREAD

**Issue by axiom41** [GDATASoftwareAG/robotframework-flaui#69]
Hello.
When a version compatible with Python 3.10.x will be released?

Thanks for your support.

Trying to install v1.7.3 i get the following error:

**Collecting robotframework-flaui
  Using cached robotframework-flaui-1.7.3.tar.gz (255 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-58slm_8v\robotframework-flaui_4ced249a34f245c5bad49df92693aa4f\setup.py", line 34, in <module>
          with open("requirements.txt", "r") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      ---------------------Branch Informations---------------------
      Release: False
      APPVEYOR_REPO_TAG: false
      APPVEYOR_REPO_TAG_NAME: 0
      APPVEYOR_BUILD_VERSION: 0
      APPVEYOR_BUILD_NUMBER: 0
      -------------------------------------------------------------
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.**

**Comment by Nepitwin** [comment]
Hi @axiom41 ,

this depends on Python.Net Wrapper (https://github.com/pythonnet/pythonnet) which currently supports Python 3.8, 3.7.

Python.Net Pre Release also include additional release candidates which supports python 3.9 and 3.10.

Robotframework-Flaui is already prepared if this release will be published to create a new majore release to support this python versions.

https://ci.appveyor.com/project/GDATACyberDefenseAG/robotframework-flaui/builds/44527736

But if you want you can pre test this version which includes the usage from Python.Net 3.0rc3

[robotframework_flaui-1.0.505rc505-cp310-cp310.zip](https://github.com/GDATASoftwareAG/robotframework-flaui/files/9387586/robotframework_flaui-1.0.505rc505-cp310-cp310.zip)

**Comment by DimitriMirsot** [comment]
@Nepitwin I saw that this item was resolved but I'm still getting the error, What could I be missing?
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Dimitri Miranda\AppData\Local\Temp\pip-install-etu3r4r7\robotframework-flaui_1b3e18bc69094be9baca29c37c12b20c\setup.py", line 34, in <module>
          with open("requirements.txt", "r") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      ---------------------Branch Informations---------------------
      Release: False
      APPVEYOR_REPO_TAG: false
      APPVEYOR_REPO_TAG_NAME: 0
      APPVEYOR_BUILD_VERSION: 0
      APPVEYOR_BUILD_NUMBER: 0
      -------------------------------------------------------------
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by Nepitwin** [comment]
@DimitriMirsot 

I decide to releaes this new major version by 2.0.0. This will be build now and released to pypi afterwards this should now work.
